### ISSUE TITLE
Odd issue with Period

### ISSUE THREAD

**Issue by phenaff** [enthought/pyql#209]
A fresh build of QuantLib & pyql gives me this odd error:
```python
>>> 3*Months 
```
returns an int!

```python
>>> from quantlib.time.api import Months, Period
>>> p1 = Period(3, Months)
>>> p1
Period('3M')
>>> todays_date
Date('2017-01-29T00:00:00,000000')
>>> todays_date + p1
Date('2017-04-29T00:00:00,000000')
>>> todays_date + 3*Months
Date('2017-02-04T00:00:00,000000')
>>> p2 = 3*Months
>>> type(p2)
<type 'int'>
```
My setup:
Ubuntu 14.04
Cython 0.27.3
QuantLib-1.11.0 compiled with --enable-intraday
Python 2.7 

Obviously, there is something wrong with my build. Would anyone have an hint on what's going on?
Thanks in advance

**Comment by thrasibule** [comment]
Months is an enum, so it converts to an int. It's the same in C++. Did this ever work in python? This work on the other hand:

```python
>> 3 * Period(1, Months)
Period('3M')

**Comment by thrasibule** [comment]
Test is running fine here on python 3.6 (and travis passes both on python 2.7 and python 3.4, so that's a lot of configurations) Which line specifically is causing the segfault? Are you sure this is the cause? We should fix the test regardless.

**Comment by phenaff** [comment]
I have submitted a PR that fixes the tests. I still get a segfault on my PC, but not sure anymore where it's coming from. I'll investigate, probably some config issue on my side.
