### ISSUE TITLE
error: ‘RelativePriceError’ is not a member of ‘QuantLib::CalibrationHelper’

### ISSUE THREAD

**Issue by Aspire1Inspire2** [enthought/pyql#259]
I am building with Quantlib 1.19 and conda python3.7 env.

Got the following error:

```
gcc -pthread -B /opt/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/usr/include -I. -I./cpp_layer -I/opt/miniconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/miniconda3/include/python3.7m -c quantlib/models/calibration_helper.cpp -o build/temp.linux-x86_64-3.7/quantlib/models/calibration_helper.o
quantlib/models/calibration_helper.cpp:1131:100: error: ‘RelativePriceError’ is not a member of ‘QuantLib::CalibrationHelper’
 1131 |   __pyx_e_8quantlib_6models_18calibration_helper_RelativePriceError = QuantLib::CalibrationHelper::RelativePriceError,
      |                                                                                                    ^~~~~~~~~~~~~~~~~~
quantlib/models/calibration_helper.cpp:1132:92: error: ‘PriceError’ is not a member of ‘QuantLib::CalibrationHelper’
 1132 |   __pyx_e_8quantlib_6models_18calibration_helper_PriceError = QuantLib::CalibrationHelper::PriceError,
      |                                                                                            ^~~~~~~~~~
quantlib/models/calibration_helper.cpp:1133:97: error: ‘ImpliedVolError’ is not a member of ‘QuantLib::CalibrationHelper’
 1133 |   __pyx_e_8quantlib_6models_18calibration_helper_ImpliedVolError = QuantLib::CalibrationHelper::ImpliedVolError
      |                                                                                                 ^~~~~~~~~~~~~~~
quantlib/models/calibration_helper.cpp: In function ‘PyObject* __pyx_pf_8quantlib_6models_18calibration_helper_17CalibrationHelper_2set_pricing_engine(__pyx_obj_8quantlib_6models_18calibration_helper_CalibrationHelper*, __pyx_obj_8quantlib_14pricingengines_6engine_PricingEngine*)’:
quantlib/models/calibration_helper.cpp:2005:35: error: ‘boost::shared_ptr<QuantLib::CalibrationHelper>::element_type’ {aka ‘class QuantLib::CalibrationHelper’} has no member named ‘setPricingEngine’
 2005 |     __pyx_v_self->_thisptr.get()->setPricingEngine((*__pyx_v_engine->_thisptr));
      |                                   ^~~~~~~~~~~~~~~~
quantlib/models/calibration_helper.cpp: In function ‘PyObject* __pyx_pf_8quantlib_6models_18calibration_helper_17CalibrationHelper_4model_value(__pyx_obj_8quantlib_6models_18calibration_helper_CalibrationHelper*)’:
quantlib/models/calibration_helper.cpp:2072:47: error: ‘boost::shared_ptr<QuantLib::CalibrationHelper>::element_type’ {aka ‘class QuantLib::CalibrationHelper’} has no member named ‘modelValue’
 2072 |     __pyx_t_1 = __pyx_v_self->_thisptr.get()->modelValue();
      |                                               ^~~~~~~~~~
quantlib/models/calibration_helper.cpp: In function ‘PyObject* __pyx_pf_8quantlib_6models_18calibration_helper_17CalibrationHelper_6black_price(__pyx_obj_8quantlib_6models_18calibration_helper_CalibrationHelper*, double)’:
quantlib/models/calibration_helper.cpp:2156:47: error: ‘boost::shared_ptr<QuantLib::CalibrationHelper>::element_type’ {aka ‘class QuantLib::CalibrationHelper’} has no member named ‘blackPrice’
 2156 |     __pyx_t_1 = __pyx_v_self->_thisptr.get()->blackPrice(__pyx_v_volatility);
      |                                               ^~~~~~~~~~
quantlib/models/calibration_helper.cpp: In function ‘PyObject* __pyx_pf_8quantlib_6models_18calibration_helper_17CalibrationHelper_8market_value(__pyx_obj_8quantlib_6models_18calibration_helper_CalibrationHelper*)’:
quantlib/models/calibration_helper.cpp:2227:47: error: ‘boost::shared_ptr<QuantLib::CalibrationHelper>::element_type’ {aka ‘class QuantLib::CalibrationHelper’} has no member named ‘marketValue’
 2227 |     __pyx_t_1 = __pyx_v_self->_thisptr.get()->marketValue();
      |                                               ^~~~~~~~~~~
quantlib/models/calibration_helper.cpp: In function ‘PyObject* __pyx_pf_8quantlib_6models_18calibration_helper_17CalibrationHelper_12impliedVolatility(__pyx_obj_8quantlib_6models_18calibration_helper_CalibrationHelper*, __pyx_t_8quantlib_6models_18calibration_helper_Real, __pyx_t_8quantlib_6models_18calibration_helper_Real, __pyx_t_8quantlib_6models_18calibration_helper_Size, __pyx_t_8quantlib_6models_18calibration_helper_Volatility, __pyx_t_8quantlib_6models_18calibration_helper_Volatility)’:
quantlib/models/calibration_helper.cpp:2459:47: error: ‘boost::shared_ptr<QuantLib::CalibrationHelper>::element_type’ {aka ‘class QuantLib::CalibrationHelper’} has no member named ‘impliedVolatility’
 2459 |     __pyx_t_1 = __pyx_v_self->_thisptr.get()->impliedVolatility(__pyx_v_targetValue, __pyx_v_accuracy, __pyx_v_maxEvaluations, __pyx_v_minVol, __pyx_v_maxVol);
      |                                               ^~~~~~~~~~~~~~~~~
error: command 'gcc' failed with exit status 1
make: *** [Makefile:2: build] Error 1
```

Could anyone lend some help?

**Comment by thrasibule** [comment]
Can you try with this [PR](https://github.com/enthought/pyql/pull/257)? Should be fixed there.

**Comment by Aspire1Inspire2** [comment]
I tried the pull request, but still get the following errors:

```
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:1850:8: note: in expansion of macro ‘CYTHON_INLINE’
 1850 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value);
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:1850:80: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 1850 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value);
      |                                                                                ^~~~
      |                                                                                Hours
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:1853:8: note: in expansion of macro ‘CYTHON_INLINE’
 1853 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value);
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:1853:82: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 1853 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value);
      |                                                                                  ^~~~~~
      |                                                                                  Minutes
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:1856:8: note: in expansion of macro ‘CYTHON_INLINE’
 1856 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value);
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:1856:82: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 1856 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value);
      |                                                                                  ^~~~~~
      |                                                                                  Seconds
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:1859:8: note: in expansion of macro ‘CYTHON_INLINE’
 1859 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value);
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:1859:87: error: ‘Millisecond’ is not a member of ‘QuantLib’; did you mean ‘Milliseconds’?
 1859 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value);
      |                                                                                       ^~~~~~~~~~~
      |                                                                                       Milliseconds
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:1862:8: note: in expansion of macro ‘CYTHON_INLINE’
 1862 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value);
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:1862:87: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
 1862 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value);
      |                                                                                       ^~~~~~~~~~~
      |                                                                                       Microseconds
quantlib/time/date.cpp:1886:32: error: ‘Hour’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Hours’?
 1886 | static CYTHON_INLINE QuantLib::Hour __Pyx_PyInt_As_QuantLib_3a__3a_Hour(PyObject *);
      |                                ^~~~
      |                                Hours
quantlib/time/date.cpp:1889:32: error: ‘Minute’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Minutes’?
 1889 | static CYTHON_INLINE QuantLib::Minute __Pyx_PyInt_As_QuantLib_3a__3a_Minute(PyObject *);
      |                                ^~~~~~
      |                                Minutes
quantlib/time/date.cpp:1892:32: error: ‘Second’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Seconds’?
 1892 | static CYTHON_INLINE QuantLib::Second __Pyx_PyInt_As_QuantLib_3a__3a_Second(PyObject *);
      |                                ^~~~~~
      |                                Seconds
quantlib/time/date.cpp:1895:32: error: ‘Millisecond’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Milliseconds’?
 1895 | static CYTHON_INLINE QuantLib::Millisecond __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(PyObject *);
      |                                ^~~~~~~~~~~
      |                                Milliseconds
quantlib/time/date.cpp:1898:32: error: ‘Microsecond’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Microseconds’?
 1898 | static CYTHON_INLINE QuantLib::Microsecond __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(PyObject *);
      |                                ^~~~~~~~~~~
      |                                Microseconds
quantlib/time/date.cpp: In function ‘int __pyx_pf_8quantlib_4time_4date_4Date___init__(__pyx_obj_8quantlib_4time_4date_Date*, PyObject*)’:
quantlib/time/date.cpp:5370:13: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5370 |   QuantLib::Hour __pyx_t_17;
      |             ^~~~
      |             Hours
quantlib/time/date.cpp:5371:13: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 5371 |   QuantLib::Minute __pyx_t_18;
      |             ^~~~~~
      |             Minutes
quantlib/time/date.cpp:5372:13: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 5372 |   QuantLib::Second __pyx_t_19;
      |             ^~~~~~
      |             Seconds
quantlib/time/date.cpp:5374:13: error: ‘Millisecond’ is not a member of ‘QuantLib’; did you mean ‘Milliseconds’?
 5374 |   QuantLib::Millisecond __pyx_t_21;
      |             ^~~~~~~~~~~
      |             Milliseconds
quantlib/time/date.cpp:5376:13: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
 5376 |   QuantLib::Microsecond __pyx_t_23;
      |             ^~~~~~~~~~~
      |             Microseconds
quantlib/time/date.cpp:5689:5: error: ‘__pyx_t_17’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5689 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5689:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Hour’ was not declared in this scope; did you mean ‘__Pyx_PyInt_As_QuantLib_3a__3a_Year’?
 5689 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_As_QuantLib_3a__3a_Year
quantlib/time/date.cpp:5689:110: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5689 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                                                                                                              ^~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5690:5: error: ‘__pyx_t_18’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5690 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5690:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Minute’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Minute’?
 5690 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Minute
quantlib/time/date.cpp:5690:114: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 5690 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5691:5: error: ‘__pyx_t_19’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5691 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5691:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Second’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Second’?
 5691 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Second
quantlib/time/date.cpp:5691:114: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 5691 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 307, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5700:157: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5700 | __pyx_v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), 0, 0));
      |                                                                                                                                                         ^~~~
      |                                                                                                                                                         Hours
quantlib/time/date.cpp:5700:162: error: expected ‘)’ before ‘__pyx_t_17’
 5700 | _v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), 0, 0));
      |                                                                                                                                        ~                ^~~~~~~~~~
      |                                                                                                                                                         )
quantlib/time/date.cpp:5700:245: error: expected ‘)’ before ‘;’ token
 5700 | Lib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), 0, 0));
      |                                                                                                                                                         ^
      |                                                                                                                                                         )
quantlib/time/date.cpp:5798:5: error: ‘__pyx_t_17’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5798 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5798:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Hour’ was not declared in this scope; did you mean ‘__Pyx_PyInt_As_QuantLib_3a__3a_Year’?
 5798 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_As_QuantLib_3a__3a_Year
quantlib/time/date.cpp:5798:110: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5798 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                                                                                                              ^~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5799:5: error: ‘__pyx_t_18’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5799 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5799:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Minute’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Minute’?
 5799 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Minute
quantlib/time/date.cpp:5799:114: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 5799 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5800:5: error: ‘__pyx_t_19’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5800 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5800:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Second’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Second’?
 5800 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Second
quantlib/time/date.cpp:5800:114: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 5800 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5801:5: error: ‘__pyx_t_21’ was not declared in this scope; did you mean ‘__pyx_t_24’?
 5801 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_24
quantlib/time/date.cpp:5801:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Millisecond’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Millisecond’?
 5801 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond
quantlib/time/date.cpp:5801:114: error: ‘Millisecond’ is not a member of ‘QuantLib’; did you mean ‘Milliseconds’?
 5801 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 311, __pyx_L1_error)
      |                                                                                                                  ^~~~~~~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5810:157: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5810 | __pyx_v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), 0));
      |                                                                                                                                                         ^~~~
      |                                                                                                                                                         Hours
quantlib/time/date.cpp:5810:162: error: expected ‘)’ before ‘__pyx_t_17’
 5810 | _v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), 0));
      |                                                                                                                                        ~                ^~~~~~~~~~
      |                                                                                                                                                         )
quantlib/time/date.cpp:5810:279: error: expected ‘)’ before ‘;’ token
 5810 | :Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), 0));
      |                                                                                                                                                         ^
      |                                                                                                                                                         )
quantlib/time/date.cpp:5912:5: error: ‘__pyx_t_17’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5912 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5912:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Hour’ was not declared in this scope; did you mean ‘__Pyx_PyInt_As_QuantLib_3a__3a_Year’?
 5912 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_As_QuantLib_3a__3a_Year
quantlib/time/date.cpp:5912:110: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5912 |     __pyx_t_17 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_v_hours); if (unlikely((__pyx_t_17 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                                                                                                              ^~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5913:5: error: ‘__pyx_t_18’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5913 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5913:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Minute’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Minute’?
 5913 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Minute
quantlib/time/date.cpp:5913:114: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 5913 |     __pyx_t_18 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_v_minutes); if (unlikely((__pyx_t_18 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5914:5: error: ‘__pyx_t_19’ was not declared in this scope; did you mean ‘__pyx_t_16’?
 5914 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_16
quantlib/time/date.cpp:5914:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Second’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Second’?
 5914 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Second
quantlib/time/date.cpp:5914:114: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 5914 |     __pyx_t_19 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_v_seconds); if (unlikely((__pyx_t_19 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                                                                                                                  ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5915:5: error: ‘__pyx_t_21’ was not declared in this scope; did you mean ‘__pyx_t_24’?
 5915 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_24
quantlib/time/date.cpp:5915:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Millisecond’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Millisecond’?
 5915 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond
quantlib/time/date.cpp:5915:114: error: ‘Millisecond’ is not a member of ‘QuantLib’; did you mean ‘Milliseconds’?
 5915 |     __pyx_t_21 = __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(__pyx_v_ms); if (unlikely((__pyx_t_21 == ((QuantLib::Millisecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 315, __pyx_L1_error)
      |                                                                                                                  ^~~~~~~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5924:5: error: ‘__pyx_t_23’ was not declared in this scope; did you mean ‘__pyx_t_24’?
 5924 |     __pyx_t_23 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_v_mus); if (unlikely((__pyx_t_23 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 316, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_24
quantlib/time/date.cpp:5924:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Microsecond’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Microsecond’?
 5924 |     __pyx_t_23 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_v_mus); if (unlikely((__pyx_t_23 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 316, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond
quantlib/time/date.cpp:5924:115: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
 5924 |     __pyx_t_23 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_v_mus); if (unlikely((__pyx_t_23 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 316, __pyx_L1_error)
      |                                                                                                                   ^~~~~~~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:5933:157: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 5933 | __pyx_v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), ((QuantLib::Microsecond)__pyx_t_23)));
      |                                                                                                                                                         ^~~~
      |                                                                                                                                                         Hours
quantlib/time/date.cpp:5933:162: error: expected ‘)’ before ‘__pyx_t_17’
 5933 | _v_self->_thisptr.reset(new QuantLib::Date(((QuantLib::Day)__pyx_t_6), ((enum QuantLib::Month)__pyx_t_7), ((QuantLib::Year)__pyx_t_8), ((QuantLib::Hour)__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), ((QuantLib::Microsecond)__pyx_t_23)));
      |                                                                                                                                        ~                ^~~~~~~~~~
      |                                                                                                                                                         )
quantlib/time/date.cpp:5933:313: error: expected ‘)’ before ‘;’ token
 5933 | )__pyx_t_17), ((QuantLib::Minute)__pyx_t_18), ((QuantLib::Second)__pyx_t_19), ((QuantLib::Millisecond)__pyx_t_21), ((QuantLib::Microsecond)__pyx_t_23)));
      |                                                                                                                                                         ^
      |                                                                                                                                                         )
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_5hours___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6610:83: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘hours’
 6610 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Hour(__pyx_v_self->_thisptr.get()->hours()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 352, __pyx_L1_error)
      |                                                                                   ^~~~~
quantlib/time/date.cpp:6610:90: error: ‘__Pyx_PyInt_From_QuantLib_3a__3a_Hour’ cannot be used as a function
 6610 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Hour(__pyx_v_self->_thisptr.get()->hours()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 352, __pyx_L1_error)
      |                                                                                          ^
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_7minutes___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6673:85: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘minutes’
 6673 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Minute(__pyx_v_self->_thisptr.get()->minutes()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 356, __pyx_L1_error)
      |                                                                                     ^~~~~~~
quantlib/time/date.cpp:6673:94: error: ‘__Pyx_PyInt_From_QuantLib_3a__3a_Minute’ cannot be used as a function
 6673 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Minute(__pyx_v_self->_thisptr.get()->minutes()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 356, __pyx_L1_error)
      |                                                                                              ^
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_7seconds___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6736:85: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘seconds’
 6736 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Second(__pyx_v_self->_thisptr.get()->seconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 360, __pyx_L1_error)
      |                                                                                     ^~~~~~~
quantlib/time/date.cpp:6736:94: error: ‘__Pyx_PyInt_From_QuantLib_3a__3a_Second’ cannot be used as a function
 6736 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Second(__pyx_v_self->_thisptr.get()->seconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 360, __pyx_L1_error)
      |                                                                                              ^
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_12milliseconds___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6799:90: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘milliseconds’
 6799 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(__pyx_v_self->_thisptr.get()->milliseconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 364, __pyx_L1_error)
      |                                                                                          ^~~~~~~~~~~~
quantlib/time/date.cpp:6799:104: error: ‘__Pyx_PyInt_From_QuantLib_3a__3a_Millisecond’ cannot be used as a function
 6799 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(__pyx_v_self->_thisptr.get()->milliseconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 364, __pyx_L1_error)
      |                                                                                                        ^
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_12microseconds___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6862:90: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘microseconds’
 6862 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(__pyx_v_self->_thisptr.get()->microseconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 368, __pyx_L1_error)
      |                                                                                          ^~~~~~~~~~~~
quantlib/time/date.cpp:6862:104: error: ‘__Pyx_PyInt_From_QuantLib_3a__3a_Microsecond’ cannot be used as a function
 6862 |   __pyx_t_1 = __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(__pyx_v_self->_thisptr.get()->microseconds()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 368, __pyx_L1_error)
      |                                                                                                        ^
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_15fraction_of_day___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6925:64: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘fractionOfDay’
 6925 |   __pyx_t_1 = PyFloat_FromDouble(__pyx_v_self->_thisptr.get()->fractionOfDay()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 372, __pyx_L1_error)
      |                                                                ^~~~~~~~~~~~~
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_18fraction_of_second___get__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:6988:64: error: ‘boost::shared_ptr<QuantLib::Date>::element_type’ {aka ‘class QuantLib::Date’} has no member named ‘fractionOfSecond’
 6988 |   __pyx_t_1 = PyFloat_FromDouble(__pyx_v_self->_thisptr.get()->fractionOfSecond()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 376, __pyx_L1_error)
      |                                                                ^~~~~~~~~~~~~~~~
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_4Date_4__repr__(__pyx_obj_8quantlib_4time_4date_Date*)’:
quantlib/time/date.cpp:7138:55: error: ‘iso_datetime’ is not a member of ‘QuantLib::io’; did you mean ‘iso_date’?
 7138 |   (void)((((__pyx_v_ss << __pyx_t_1) << QuantLib::io::iso_datetime((*__pyx_v_self->_thisptr))) << __pyx_t_2));
      |                                                       ^~~~~~~~~~~~
      |                                                       iso_date
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_28local_date_time(PyObject*)’:
quantlib/time/date.cpp:9295:33: error: ‘localDateTime’ is not a member of ‘QuantLib::Date’
 9295 |   __pyx_v_ldt = QuantLib::Date::localDateTime();
      |                                 ^~~~~~~~~~~~~
quantlib/time/date.cpp: In function ‘PyObject* __pyx_pf_8quantlib_4time_4date_30universal_date_time(PyObject*)’:
quantlib/time/date.cpp:9370:33: error: ‘universalDateTime’ is not a member of ‘QuantLib::Date’
 9370 |   __pyx_v_utc = QuantLib::Date::universalDateTime();
      |                                 ^~~~~~~~~~~~~~~~~
quantlib/time/date.cpp: In function ‘QuantLib::Date __pyx_f_8quantlib_4time_4date__qldate_from_pydate(PyObject*)’:
quantlib/time/date.cpp:9696:13: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 9696 |   QuantLib::Hour __pyx_t_7;
      |             ^~~~
      |             Hours
quantlib/time/date.cpp:9697:13: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 9697 |   QuantLib::Minute __pyx_t_8;
      |             ^~~~~~
      |             Minutes
quantlib/time/date.cpp:9698:13: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 9698 |   QuantLib::Second __pyx_t_9;
      |             ^~~~~~
      |             Seconds
quantlib/time/date.cpp:9699:13: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
 9699 |   QuantLib::Microsecond __pyx_t_10;
      |             ^~~~~~~~~~~
      |             Microseconds
quantlib/time/date.cpp:9746:5: error: ‘__pyx_t_7’ was not declared in this scope; did you mean ‘__pyx_t_6’?
 9746 |     __pyx_t_7 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_t_3); if (unlikely((__pyx_t_7 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |     ^~~~~~~~~
      |     __pyx_t_6
quantlib/time/date.cpp:9746:17: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Hour’ was not declared in this scope; did you mean ‘__Pyx_PyInt_As_QuantLib_3a__3a_Year’?
 9746 |     __pyx_t_7 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_t_3); if (unlikely((__pyx_t_7 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 __Pyx_PyInt_As_QuantLib_3a__3a_Year
quantlib/time/date.cpp:9746:104: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 9746 |     __pyx_t_7 = __Pyx_PyInt_As_QuantLib_3a__3a_Hour(__pyx_t_3); if (unlikely((__pyx_t_7 == ((QuantLib::Hour)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                                                                                                        ^~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:9750:5: error: ‘__pyx_t_8’ was not declared in this scope; did you mean ‘__pyx_t_6’?
 9750 |     __pyx_t_8 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_t_3); if (unlikely((__pyx_t_8 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |     ^~~~~~~~~
      |     __pyx_t_6
quantlib/time/date.cpp:9750:17: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Minute’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Minute’?
 9750 |     __pyx_t_8 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_t_3); if (unlikely((__pyx_t_8 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 __Pyx_PyInt_From_QuantLib_3a__3a_Minute
quantlib/time/date.cpp:9750:106: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
 9750 |     __pyx_t_8 = __Pyx_PyInt_As_QuantLib_3a__3a_Minute(__pyx_t_3); if (unlikely((__pyx_t_8 == ((QuantLib::Minute)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                                                                                                          ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:9754:5: error: ‘__pyx_t_9’ was not declared in this scope; did you mean ‘__pyx_t_6’?
 9754 |     __pyx_t_9 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_t_3); if (unlikely((__pyx_t_9 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |     ^~~~~~~~~
      |     __pyx_t_6
quantlib/time/date.cpp:9754:17: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Second’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Second’?
 9754 |     __pyx_t_9 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_t_3); if (unlikely((__pyx_t_9 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 __Pyx_PyInt_From_QuantLib_3a__3a_Second
quantlib/time/date.cpp:9754:106: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
 9754 |     __pyx_t_9 = __Pyx_PyInt_As_QuantLib_3a__3a_Second(__pyx_t_3); if (unlikely((__pyx_t_9 == ((QuantLib::Second)-1)) && PyErr_Occurred())) __PYX_ERR(0, 556, __pyx_L1_error)
      |                                                                                                          ^~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:9766:5: error: ‘__pyx_t_10’ was not declared in this scope; did you mean ‘__pyx_t_11’?
 9766 |     __pyx_t_10 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_t_3); if (unlikely((__pyx_t_10 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 557, __pyx_L1_error)
      |     ^~~~~~~~~~
      |     __pyx_t_11
quantlib/time/date.cpp:9766:18: error: ‘__Pyx_PyInt_As_QuantLib_3a__3a_Microsecond’ was not declared in this scope; did you mean ‘__Pyx_PyInt_From_QuantLib_3a__3a_Microsecond’?
 9766 |     __pyx_t_10 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_t_3); if (unlikely((__pyx_t_10 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 557, __pyx_L1_error)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond
quantlib/time/date.cpp:9766:113: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
 9766 |     __pyx_t_10 = __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(__pyx_t_3); if (unlikely((__pyx_t_10 == ((QuantLib::Microsecond)-1)) && PyErr_Occurred())) __PYX_ERR(0, 557, __pyx_L1_error)
      |                                                                                                                 ^~~~~~~~~~~
quantlib/time/date.cpp:870:43: note: in definition of macro ‘unlikely’
  870 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
quantlib/time/date.cpp:9776:178: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 9776 | ate(((QuantLib::Day)__pyx_t_4), ((enum QuantLib::Month)((enum __pyx_t_8quantlib_4time_4date_Month)__pyx_t_5)), ((QuantLib::Year)__pyx_t_6), ((QuantLib::Hour)__pyx_t_7), ((QuantLib::Minute)__pyx_t_8), ((QuantLib::Second)__pyx_t_9), 0, ((QuantLib::Microsecond)__pyx_t_10));
      |                                                                                                                                                         ^~~~
      |                                                                                                                                                         Hours
quantlib/time/date.cpp:9776:29: error: expected primary-expression before ‘(’ token
 9776 |     __pyx_r = QuantLib::Date(((QuantLib::Day)__pyx_t_4), ((enum QuantLib::Month)((enum __pyx_t_8quantlib_4time_4date_Month)__pyx_t_5)), ((QuantLib::Year)__pyx_t_6), ((QuantLib::Hour)__pyx_t_7), ((QuantLib::Minute)__pyx_t_8), ((QuantLib::Second)__pyx_t_9), 0, ((QuantLib::Microsecond)__pyx_t_10));
      |                             ^
quantlib/time/date.cpp:9776:178: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
 9776 | ate(((QuantLib::Day)__pyx_t_4), ((enum QuantLib::Month)((enum __pyx_t_8quantlib_4time_4date_Month)__pyx_t_5)), ((QuantLib::Year)__pyx_t_6), ((QuantLib::Hour)__pyx_t_7), ((QuantLib::Minute)__pyx_t_8), ((QuantLib::Second)__pyx_t_9), 0, ((QuantLib::Microsecond)__pyx_t_10));
      |                                                                                                                                                         ^~~~
      |                                                                                                                                                         Hours
quantlib/time/date.cpp:9776:183: error: expected ‘)’ before ‘__pyx_t_7’
 9776 | (QuantLib::Day)__pyx_t_4), ((enum QuantLib::Month)((enum __pyx_t_8quantlib_4time_4date_Month)__pyx_t_5)), ((QuantLib::Year)__pyx_t_6), ((QuantLib::Hour)__pyx_t_7), ((QuantLib::Minute)__pyx_t_8), ((QuantLib::Second)__pyx_t_9), 0, ((QuantLib::Microsecond)__pyx_t_10));
      |                                                                                                                                        ~                ^~~~~~~~~
      |                                                                                                                                                         )
quantlib/time/date.cpp: At global scope:
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:21570:8: note: in expansion of macro ‘CYTHON_INLINE’
21570 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value) {
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:21570:32: error: redefinition of ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour’
21570 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value) {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:1850:32: note: ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour’ previously defined here
 1850 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:21570:80: error: ‘Hour’ is not a member of ‘QuantLib’; did you mean ‘Hours’?
21570 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Hour(QuantLib::Hour value) {
      |                                                                                ^~~~
      |                                                                                Hours
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:21601:8: note: in expansion of macro ‘CYTHON_INLINE’
21601 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value) {
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:21601:32: error: redefinition of ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute’
21601 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value) {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:1853:32: note: ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute’ previously defined here
 1853 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:21601:82: error: ‘Minute’ is not a member of ‘QuantLib’; did you mean ‘Minutes’?
21601 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Minute(QuantLib::Minute value) {
      |                                                                                  ^~~~~~
      |                                                                                  Minutes
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:21632:8: note: in expansion of macro ‘CYTHON_INLINE’
21632 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value) {
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:21632:32: error: redefinition of ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second’
21632 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value) {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:1856:32: note: ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second’ previously defined here
 1856 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:21632:82: error: ‘Second’ is not a member of ‘QuantLib’; did you mean ‘Seconds’?
21632 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Second(QuantLib::Second value) {
      |                                                                                  ^~~~~~
      |                                                                                  Seconds
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:21663:8: note: in expansion of macro ‘CYTHON_INLINE’
21663 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value) {
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:21663:32: error: redefinition of ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond’
21663 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value) {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:1859:32: note: ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond’ previously defined here
 1859 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:21663:87: error: ‘Millisecond’ is not a member of ‘QuantLib’; did you mean ‘Milliseconds’?
21663 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Millisecond(QuantLib::Millisecond value) {
      |                                                                                       ^~~~~~~~~~~
      |                                                                                       Milliseconds
quantlib/time/date.cpp:335:27: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  335 |     #define CYTHON_INLINE inline
      |                           ^~~~~~
quantlib/time/date.cpp:21694:8: note: in expansion of macro ‘CYTHON_INLINE’
21694 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value) {
      |        ^~~~~~~~~~~~~
quantlib/time/date.cpp:21694:32: error: redefinition of ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond’
21694 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value) {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:1862:32: note: ‘PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond’ previously defined here
 1862 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
quantlib/time/date.cpp:21694:87: error: ‘Microsecond’ is not a member of ‘QuantLib’; did you mean ‘Microseconds’?
21694 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value) {
      |                                                                                       ^~~~~~~~~~~
      |                                                                                       Microseconds
quantlib/time/date.cpp:23048:32: error: ‘Hour’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Hours’?
23048 | static CYTHON_INLINE QuantLib::Hour __Pyx_PyInt_As_QuantLib_3a__3a_Hour(PyObject *x) {
      |                                ^~~~
      |                                Hours
quantlib/time/date.cpp:23237:32: error: ‘Minute’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Minutes’?
23237 | static CYTHON_INLINE QuantLib::Minute __Pyx_PyInt_As_QuantLib_3a__3a_Minute(PyObject *x) {
      |                                ^~~~~~
      |                                Minutes
quantlib/time/date.cpp:23426:32: error: ‘Second’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Seconds’?
23426 | static CYTHON_INLINE QuantLib::Second __Pyx_PyInt_As_QuantLib_3a__3a_Second(PyObject *x) {
      |                                ^~~~~~
      |                                Seconds
quantlib/time/date.cpp:23615:32: error: ‘Millisecond’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Milliseconds’?
23615 | static CYTHON_INLINE QuantLib::Millisecond __Pyx_PyInt_As_QuantLib_3a__3a_Millisecond(PyObject *x) {
      |                                ^~~~~~~~~~~
      |                                Milliseconds
quantlib/time/date.cpp:23804:32: error: ‘Microsecond’ in namespace ‘QuantLib’ does not name a type; did you mean ‘Microseconds’?
23804 | static CYTHON_INLINE QuantLib::Microsecond __Pyx_PyInt_As_QuantLib_3a__3a_Microsecond(PyObject *x) {
      |                                ^~~~~~~~~~~
      |                                Microseconds
error: command 'gcc' failed with exit status 1
make: *** [Makefile:2: build] Error 1
```

**Comment by thrasibule** [comment]
You're being bit by #255  now :( You need to build quantlib with --enable-intraday. How did you install it by the way?

**Comment by Aspire1Inspire2** [comment]
It works after turning intraday feature on with the aforementioned pull request.
Thanks for your help!

I am building both Quantlib and PyQl from its git repo.
I can confirm that this pull request works for Quantlib 1.20 as well.
